### ISSUE TITLE
Give a Shout-out

### ISSUE THREAD

**Issue by MatthewZMD** [swhalemwo/obr-viz#1]
I wanna give a shout-out to you, @swhalemwo! I am glad you find EAF to be useful. I added obr-viz to the README so more people will see this package! This is a very cool package, I can see people using org-brain will use it, you might want to let org-brain's people know too @Kungsgeten :smiley:

**Comment by Kungsgeten** [comment]
Yes, it looks nice. I haven't used EAF and from what I understand `obr-viz` is still in early development? I'll gladly link to it from the `org-brain` README when @swhalemwo feels its usable.

**Comment by swhalemwo** [comment]
thanks you for the shoutout @MatthewZMD , and adding it to your README, i'm glad you like it! it is indeed still somewhat early in development (in particular designing guis seems to involve quite some more than i would had expected); i'll let you @Kungsgeten know when it's usable :)
